version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 
  complex-logic:
    enabled: true
    config:
      threshold: 
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 
  method-count:
    enabled: true
    config:
      threshold: 
  method-lines:
    enabled: true
    config:
      threshold: 
  nested-control-flow:
    enabled: true
    config:
      threshold: 
  return-statements:
    enabled: true
    config:
      threshold: 
  similar-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
plugins:
 rubocop:
  enabled: true
 eslint:
  enabled: true
exclude_patterns:
- "ConfTools/"
- "installBDD/"
- "LibJS/"
- "scripts/"
- "src/it/"
- "src/test/"
- "src/site"
- "src/main/javadoc"
- "src/main/resources"

