export enum ContributorTypesEnum {
    ContactPerson="Contact Person",
    DataCollector="Data Collector",
    DataCurator="Data Curator",
    DataManager="Data Manager",
    Distributor="Distributor",
    Editor="Editor",
    HostingInstitution="Hosting Institution",
    Other="Other",
    Producer="Producer",
    ProjectLeader="Project Leader",
    ProjectManager="Project Manager",
    ProjectMember="Project Member",
    RegistrationAgency="Registration Agency",
    RegistrationAuthority="Registration Authority",
    RelatedPerson="Related Person",
    ResearchGroup="Research Group",
    RightsHolder="Rights Holder",
    Researcher="Researcher",
    Sponsor="Sponsor",
    Supervisor="Supervisor",
    WorkPackageLeader="Work Package Leader"
}