CREATE USER doiserver WITH ENCRYPTED PASSWORD 'md5249656fe86cbd179a45c21703b0df719';
CREATE DATABASE doidb;
\connect doidb;
CREATE TABLE T_DOI_USERS (
 username varchar(255) NOT NULL,
 admin boolean NOT NULL,
 email varchar(255),
 PRIMARY KEY (username)
);

CREATE TABLE T_DOI_PROJECT (
 suffix int NOT NULL,
 projectname varchar(1024) NOT NULL,
 PRIMARY KEY (suffix) 
);

CREATE TABLE T_DOI_ASSIGNATIONS (
 username varchar(255) NOT NULL,
 suffix int NOT NULL,
 PRIMARY KEY (username, suffix)
);

CREATE TABLE T_DOI_TOKENS (
 token varchar(255) NOT NULL,
 PRIMARY KEY (token)
);

GRANT INSERT,DELETE,SELECT,UPDATE ON T_DOI_USERS TO doiserver;
GRANT INSERT,DELETE,SELECT,UPDATE ON T_DOI_PROJECT TO doiserver;
GRANT INSERT,DELETE,SELECT,UPDATE ON T_DOI_ASSIGNATIONS TO doiserver;
GRANT INSERT,DELETE,SELECT,UPDATE ON T_DOI_TOKENS TO doiserver;
