//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.11 at 02:45:17 PM CEST 
//
package org.datacite.schema.kernel_4;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the org.datacite.schema.kernel_4 package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ResourceDescriptionsDescriptionBr_QNAME = new QName(
            "http://datacite.org/schema/kernel-4", "br");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: org.datacite.schema.kernel_4
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Resource }
     *
     * @return the resource
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link Resource.RelatedItems }
     * 
     */
    public Resource.RelatedItems createResourceRelatedItems() {
        return new Resource.RelatedItems();
    }

    /**
     * Create an instance of {@link Resource.RelatedItems.RelatedItem }
     * 
     */
    public Resource.RelatedItems.RelatedItem createResourceRelatedItemsRelatedItem() {
        return new Resource.RelatedItems.RelatedItem();
    }

    /**
     * Create an instance of {@link Resource.RelatedItems.RelatedItem.Contributors }
     * 
     */
    public Resource.RelatedItems.RelatedItem.Contributors createResourceRelatedItemsRelatedItemContributors() {
        return new Resource.RelatedItems.RelatedItem.Contributors();
    }

    /**
     * Create an instance of {@link Resource.RelatedItems.RelatedItem.Contributors.Contributor }
     * 
     */
    public Resource.RelatedItems.RelatedItem.Contributors.Contributor createResourceRelatedItemsRelatedItemContributorsContributor() {
        return new Resource.RelatedItems.RelatedItem.Contributors.Contributor();
    }

    /**
     * Create an instance of {@link Resource.RelatedItems.RelatedItem.Titles }
     * 
     */
    public Resource.RelatedItems.RelatedItem.Titles createResourceRelatedItemsRelatedItemTitles() {
        return new Resource.RelatedItems.RelatedItem.Titles();
    }

    /**
     * Create an instance of {@link Resource.RelatedItems.RelatedItem.Creators }
     * 
     */
    public Resource.RelatedItems.RelatedItem.Creators createResourceRelatedItemsRelatedItemCreators() {
        return new Resource.RelatedItems.RelatedItem.Creators();
    }

    /**
     * Create an instance of {@link Resource.RelatedItems.RelatedItem.Creators.Creator }
     * 
     */
    public Resource.RelatedItems.RelatedItem.Creators.Creator createResourceRelatedItemsRelatedItemCreatorsCreator() {
        return new Resource.RelatedItems.RelatedItem.Creators.Creator();
    }

    /**
     * Create an instance of {@link Resource.FundingReferences }
     *
     * @return the FundingReferences
     */
    public Resource.FundingReferences createResourceFundingReferences() {
        return new Resource.FundingReferences();
    }

    /**
     * Create an instance of {@link Resource.FundingReferences.FundingReference
     * }
     *
     * @return the FundingReference
     */
    public Resource.FundingReferences.FundingReference createResourceFundingReferencesFundingReference() {
        return new Resource.FundingReferences.FundingReference();
    }

    /**
     * Create an instance of {@link Resource.GeoLocations }
     *
     * @return the GeoLocations
     */
    public Resource.GeoLocations createResourceGeoLocations() {
        return new Resource.GeoLocations();
    }

    /**
     * Create an instance of {@link Resource.GeoLocations.GeoLocation }
     *
     * @return the GeoLocation
     */
    public Resource.GeoLocations.GeoLocation createResourceGeoLocationsGeoLocation() {
        return new Resource.GeoLocations.GeoLocation();
    }

    /**
     * Create an instance of {@link Resource.Descriptions }
     *
     * @return the Descriptions
     */
    public Resource.Descriptions createResourceDescriptions() {
        return new Resource.Descriptions();
    }

    /**
     * Create an instance of {@link Resource.Descriptions.Description }
     * 
     */
    public Resource.Descriptions.Description createResourceDescriptionsDescription() {
        return new Resource.Descriptions.Description();
    }

    /**
     * Create an instance of {@link Resource.RightsList }
     *
     * @return the RightsList
     */
    public Resource.RightsList createResourceRightsList() {
        return new Resource.RightsList();
    }

    /**
     * Create an instance of {@link Resource.RelatedIdentifiers }
     *
     * @return the RelatedIdentifiers
     */
    public Resource.RelatedIdentifiers createResourceRelatedIdentifiers() {
        return new Resource.RelatedIdentifiers();
    }

    /**
     * Create an instance of {@link Resource.AlternateIdentifiers }
     *
     * @return the AlternateIdentifiers
     */
    public Resource.AlternateIdentifiers createResourceAlternateIdentifiers() {
        return new Resource.AlternateIdentifiers();
    }

    /**
     * Create an instance of {@link Resource.Dates }
     *
     * @return the Dates
     */
    public Resource.Dates createResourceDates() {
        return new Resource.Dates();
    }

    /**
     * Create an instance of {@link Resource.Contributors }
     *
     * @return the Contributors
     */
    public Resource.Contributors createResourceContributors() {
        return new Resource.Contributors();
    }

    /**
     * Create an instance of {@link Resource.Contributors.Contributor }
     *
     * @return the Contributor
     */
    public Resource.Contributors.Contributor createResourceContributorsContributor() {
        return new Resource.Contributors.Contributor();
    }

    /**
     * Create an instance of {@link Resource.Subjects }
     *
     * @return the Subjects
     */
    public Resource.Subjects createResourceSubjects() {
        return new Resource.Subjects();
    }

    /**
     * Create an instance of {@link Resource.Titles }
     *
     * @return the Titles
     */
    public Resource.Titles createResourceTitles() {
        return new Resource.Titles();
    }

    /**
     * Create an instance of {@link Resource.Creators }
     *
     * @return the Creators
     */
    public Resource.Creators createResourceCreators() {
        return new Resource.Creators();
    }

    /**
     * Create an instance of {@link Resource.Creators.Creator }
     *
     * @return the Creator
     */
    public Resource.Creators.Creator createResourceCreatorsCreator() {
        return new Resource.Creators.Creator();
    }

    /**
     * Create an instance of {@link Resource.Identifier }
     *
     * @return the Identifier
     */
    public Resource.Identifier createResourceIdentifier() {
        return new Resource.Identifier();
    }

    /**
     * Create an instance of {@link Resource.Publisher }
     * 
     */
    public Resource.Publisher createResourcePublisher() {
        return new Resource.Publisher();
    }

    /**
     * Create an instance of {@link Resource.ResourceType }
     *
     * @return the ResourceType
     */
    public Resource.ResourceType createResourceResourceType() {
        return new Resource.ResourceType();
    }

    /**
     * Create an instance of {@link Resource.Sizes }
     *
     * @return the Sizes
     */
    public Resource.Sizes createResourceSizes() {
        return new Resource.Sizes();
    }

    /**
     * Create an instance of {@link Resource.Formats }
     *
     * @return the Formats
     */
    public Resource.Formats createResourceFormats() {
        return new Resource.Formats();
    }

    /**
     * Create an instance of {@link Box }
     *
     * @return the Box
     */
    public Box createBox() {
        return new Box();
    }

    /**
     * Create an instance of {@link Point }
     *
     * @return the Point
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link Affiliation }
     * 
     */
    public Affiliation createAffiliation() {
        return new Affiliation();
    }

    /**
     * Create an instance of {@link NameIdentifier }
     * 
     */
    public NameIdentifier createNameIdentifier() {
        return new NameIdentifier();
    }

    /**
     * Create an instance of {@link Resource.RelatedItems.RelatedItem.RelatedItemIdentifier }
     * 
     */
    public Resource.RelatedItems.RelatedItem.RelatedItemIdentifier createResourceRelatedItemsRelatedItemRelatedItemIdentifier() {
        return new Resource.RelatedItems.RelatedItem.RelatedItemIdentifier();
    }

    /**
     * Create an instance of {@link Resource.RelatedItems.RelatedItem.Number }
     * 
     */
    public Resource.RelatedItems.RelatedItem.Number createResourceRelatedItemsRelatedItemNumber() {
        return new Resource.RelatedItems.RelatedItem.Number();
    }

    /**
     * Create an instance of {@link Resource.RelatedItems.RelatedItem.Contributors.Contributor.ContributorName }
     * 
     */
    public Resource.RelatedItems.RelatedItem.Contributors.Contributor.ContributorName createResourceRelatedItemsRelatedItemContributorsContributorContributorName() {
        return new Resource.RelatedItems.RelatedItem.Contributors.Contributor.ContributorName();
    }

    /**
     * Create an instance of {@link Resource.RelatedItems.RelatedItem.Titles.Title }
     * 
     */
    public Resource.RelatedItems.RelatedItem.Titles.Title createResourceRelatedItemsRelatedItemTitlesTitle() {
        return new Resource.RelatedItems.RelatedItem.Titles.Title();
    }

    /**
     * Create an instance of {@link Resource.RelatedItems.RelatedItem.Creators.Creator.CreatorName }
     * 
     */
    public Resource.RelatedItems.RelatedItem.Creators.Creator.CreatorName createResourceRelatedItemsRelatedItemCreatorsCreatorCreatorName() {
        return new Resource.RelatedItems.RelatedItem.Creators.Creator.CreatorName();
    }

    /**
     * Create an instance of {@link Resource.FundingReferences.FundingReference.FunderIdentifier }
     * 
     */
    public Resource.FundingReferences.FundingReference.FunderIdentifier createResourceFundingReferencesFundingReferenceFunderIdentifier() {
        return new Resource.FundingReferences.FundingReference.FunderIdentifier();
    }

    /**
     * Create an instance of {@link Resource.FundingReferences.FundingReference.AwardNumber
     * }
     *
     * @return the AwardNumber
     */
    public Resource.FundingReferences.FundingReference.AwardNumber createResourceFundingReferencesFundingReferenceAwardNumber() {
        return new Resource.FundingReferences.FundingReference.AwardNumber();
    }

    /**
     * Create an instance of {@link Resource.GeoLocations.GeoLocation.GeoLocationPolygon
     * }
     *
     * @return the GeoLocationPolygon
     */
    public Resource.GeoLocations.GeoLocation.GeoLocationPolygon createResourceGeoLocationsGeoLocationGeoLocationPolygon() {
        return new Resource.GeoLocations.GeoLocation.GeoLocationPolygon();
    }

    /**
     * Create an instance of {@link Resource.Descriptions.Description.Br }
     *
     * @return the Description
     */
    public Resource.Descriptions.Description.Br createResourceDescriptionsDescriptionBr() {
        return new Resource.Descriptions.Description.Br();
    }

    /**
     * Create an instance of {@link Resource.RightsList.Rights }
     *
     * @return the Rights
     */
    public Resource.RightsList.Rights createResourceRightsListRights() {
        return new Resource.RightsList.Rights();
    }

    /**
     * Create an instance of {@link Resource.RelatedIdentifiers.RelatedIdentifier
     * }
     *
     * @return the RelatedIdentifier
     */
    public Resource.RelatedIdentifiers.RelatedIdentifier createResourceRelatedIdentifiersRelatedIdentifier() {
        return new Resource.RelatedIdentifiers.RelatedIdentifier();
    }

    /**
     * Create an instance of {@link Resource.AlternateIdentifiers.AlternateIdentifier
     * }
     *
     * @return the AlternateIdentifier
     */
    public Resource.AlternateIdentifiers.AlternateIdentifier createResourceAlternateIdentifiersAlternateIdentifier() {
        return new Resource.AlternateIdentifiers.AlternateIdentifier();
    }

    /**
     * Create an instance of {@link Resource.Dates.Date }
     *
     * @return the Date
     */
    public Resource.Dates.Date createResourceDatesDate() {
        return new Resource.Dates.Date();
    }

    /**
     * Create an instance of {@link Resource.Contributors.Contributor.ContributorName
     * }
     *
     * @return the ContributorName
     */
    public Resource.Contributors.Contributor.ContributorName createResourceContributorsContributorContributorName() {
        return new Resource.Contributors.Contributor.ContributorName();
    }

    /**
     * Create an instance of {@link Resource.Subjects.Subject }
     *
     * @return the Subject
     */
    public Resource.Subjects.Subject createResourceSubjectsSubject() {
        return new Resource.Subjects.Subject();
    }

    /**
     * Create an instance of {@link Resource.Titles.Title }
     *
     * @return the Title
     */
    public Resource.Titles.Title createResourceTitlesTitle() {
        return new Resource.Titles.Title();
    }

    /**
     * Create an instance of {@link Resource.Creators.Creator.CreatorName }
     *
     * @return the CreatorName
     */
    public Resource.Creators.Creator.CreatorName createResourceCreatorsCreatorCreatorName() {
        return new Resource.Creators.Creator.CreatorName();
    }

    /**
     * Create an instance of
     * {@link JAXBElement }{@code <}{@link Resource.Descriptions.Description.Br }{@code >}}
     *
     * @param value description
     * @return the JAXBElement
     */
    @XmlElementDecl(namespace = "http://datacite.org/schema/kernel-4", name = "br", scope = Resource.Descriptions.Description.class)
    public JAXBElement<Resource.Descriptions.Description.Br> createResourceDescriptionsDescriptionBr(Resource.Descriptions.Description.Br value) {
        return new JAXBElement<Resource.Descriptions.Description.Br>(_ResourceDescriptionsDescriptionBr_QNAME, Resource.Descriptions.Description.Br.class,
                Resource.Descriptions.Description.class, value);
    }

}
