//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.11 at 02:45:17 PM CEST 
//
package org.datacite.schema.kernel_4;

import fr.cnes.doi.utils.spec.Requirement;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for resourceType.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * &nbsp;
 *
 * <pre>
 * &lt;simpleType name="resourceType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Audiovisual"/&gt;
 *     &lt;enumeration value="Book"/&gt;
 *     &lt;enumeration value="BookChapter"/&gt;
 *     &lt;enumeration value="Collection"/&gt;
 *     &lt;enumeration value="ComputationalNotebook"/&gt;
 *     &lt;enumeration value="ConferencePaper"/&gt;
 *     &lt;enumeration value="ConferenceProceeding"/&gt;
 *     &lt;enumeration value="DataPaper"/&gt;
 *     &lt;enumeration value="Dataset"/&gt;
 *     &lt;enumeration value="Dissertation"/&gt;
 *     &lt;enumeration value="Event"/&gt;
 *     &lt;enumeration value="Image"/&gt;
 *     &lt;enumeration value="InteractiveResource"/&gt;
 *     &lt;enumeration value="Journal"/&gt;
 *     &lt;enumeration value="JournalArticle"/&gt;
 *     &lt;enumeration value="Model"/&gt;
 *     &lt;enumeration value="OutputManagementPlan"/&gt;
 *     &lt;enumeration value="PeerReview"/&gt;
 *     &lt;enumeration value="PhysicalObject"/&gt;
 *     &lt;enumeration value="Preprint"/&gt;
 *     &lt;enumeration value="Report"/&gt;
 *     &lt;enumeration value="Service"/&gt;
 *     &lt;enumeration value="Software"/&gt;
 *     &lt;enumeration value="Sound"/&gt;
 *     &lt;enumeration value="Standard"/&gt;
 *     &lt;enumeration value="Text"/&gt;
 *     &lt;enumeration value="Workflow"/&gt;
 *     &lt;enumeration value="Other"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@Requirement(reqId = Requirement.DOI_SRV_010, reqName = Requirement.DOI_SRV_010_NAME)
@Requirement(reqId = Requirement.DOI_SRV_040, reqName = Requirement.DOI_SRV_040_NAME)
@Requirement(reqId = Requirement.DOI_INTER_060, reqName = Requirement.DOI_INTER_060_NAME)
@XmlType(name = "resourceType")
@XmlEnum
public enum ResourceType {

    /**
     * A series of visual representations imparting an impression of motion when
     * shown in succession. May or may not include sound. May be used for films,
     * video, etc,
     * <p>
     * Ex: http://data.datacite.org/10.7916/D8610XCB
     *
     */
    @XmlEnumValue("Audiovisual")
    AUDIOVISUAL("Audiovisual"),
    /**
     * A medium for recording information in the form
     * of writing or images, typically composed of many pages
     * bound together and protected by a cover.
     * <p>
     * Ex : &lt;resourceType resourceTypeGeneral="Book"&gt;Textbook&lt;/resourceType&gt;
     *
     */
    @XmlEnumValue("Book")
    BOOK("Book"),
    /**
     * One of the main divisions of a book.
     * <p>
     * https://doi.org/10.15122/isbn.978-2-406-09313-8.p.0639
     * https://doi.org/10.17613/m6631d
     *
     */
    @XmlEnumValue("BookChapter")
    BOOK_CHAPTER("BookChapter"),
    /**
     * An aggregation of resources of various types, or a list of resources that
     * form part of a publication. If a collection exists of a single type, use
     * the single type to describe it.
     * <p>
     * A collection of samples, or various files making up a report. Ex:
     * http://data.datacite.org/10.5284/1001038
     *
     */
    @XmlEnumValue("Collection")
    COLLECTION("Collection"),
    /**
     * A virtual notebook environment used for literate programming.
     * <p>
     * &lt;resourceType resourceTypeGeneral="ComputationalNotebook"&gt;Jupyter
     * &lt;/resourceType&gt;
     */
    @XmlEnumValue("ComputationalNotebook")
    COMPUTATIONAL_NOTEBOOK("ComputationalNotebook"),
    /**
     * Article that is written with the goal of being accepted to a conference.
     * <p>
     * &lt;resourceType resourceTypeGeneral="ConferencePaper"&gt;Experience Report
     * &lt;/resourceType&gt;
     */
    @XmlEnumValue("ConferencePaper")
    CONFERENCE_PAPER("ConferencePaper"),
    /**
     * Collection of academic papers published
     * in the context of an academic conference.
     * <p>
     * &lt;resourceType resourceTypeGeneral="ConferenceProceeding"&gt;Annual Convention
     * &lt;/resourceType&gt;
     */
    @XmlEnumValue("ConferenceProceeding")
    CONFERENCE_PROCEEDING("ConferenceProceeding"),
    @XmlEnumValue("DataPaper")
    DATA_PAPER("DataPaper"),
    /**
     * Data encoded in a defined structure.
     * <p>
     * Data file or files, Ex:http://data.datacite.org/10.4231/D39Z90B9T
     */
    @XmlEnumValue("Dataset")
    DATASET("Dataset"),
    /**
     * A written essay, treatise, or thesis, especially one written
     * by a candidate for the degree of Doctor of Philosophy.
     * <p>
     * Ex : &lt;resourceType resourceTypeGeneral="Dissertation"&gt;PhD thesis&lt;/resourceType&gt;
     */
    @XmlEnumValue("Dissertation")
    DISSERTATION("Dissertation"),
    /**
     * A non-persistent, time-based occurrence.
     * <p>
     * Descriptive information and/or content that is the basis for discovery of
     * the purpose, location, duration, and responsible agents associated with
     * an event such as a webcast or convention. Ex:
     * http://data.datacite.org/10.7269/P3RN35SZ
     */
    @XmlEnumValue("Event")
    EVENT("Event"),
    /**
     * A visual representation other than text.
     * <p>
     * Digitised or born digital images, drawings or photographs.
     * Ex:http://data.datacite.org/10.6083/M4QN65C5
     */
    @XmlEnumValue("Image")
    IMAGE("Image"),
    /**
     * A resource requiring interaction from the user to be understood,
     * executed, or experienced.
     * <p>
     * Training modules, files that require use of a viewer (e.g., Flash), or
     * query/response portals. Ex: http://data.datacite.org/10.7269/P3TB14TR
     */
    @XmlEnumValue("InteractiveResource")
    INTERACTIVE_RESOURCE("InteractiveResource"),
    @XmlEnumValue("Journal")
    JOURNAL("Journal"),
    @XmlEnumValue("JournalArticle")
    JOURNAL_ARTICLE("JournalArticle"),
    /**
     * An abstract, conceptual, graphical, mathematical or visualization model
     * that represents empirical objects, phenomena, or physical processes.
     * <p>
     * Modelled descriptions of, for example, different aspects of languages or
     * a molecular biology reaction chain. Ex:
     * http://data.datacite.org/10.5285/4D866CD2-C907-4CE2-B070-084CA9779DC2
     */
    @XmlEnumValue("Model")
    MODEL("Model"),
    /**
     * A formal document that outlines how research outputs
     * are to be handled both during a research project
     * and after the project is completed.
     * <p>
     * Includes data, software, and materials.
     * Example: &lt;resourceType resourceTypeGeneral="OutputMan agementPlan"&gt;
     *             Data Management Plan&lt;/resourceType&gt;
     */
    @XmlEnumValue("OutputManagementPlan")
    OUTPUT_MANAGEMENT_PLAN("OutputManagementPlan"),
    /**
     * Evaluation of scientific, academic, or professional work
     * by others working in the same field.
     * <p>
     * &lt;resourceType resourceTypeGeneral="PeerReview”&gt;Scientific Article&lt;/resourceType&gt;
     * Ex: https://doi.org/10.6084/m9.figshare.5742270
     */
    @XmlEnumValue("PeerReview")
    PEER_REVIEW("PeerReview"),
    /**
     * An inanimate, three-dimensional object or substance.
     * <p>
     * Artifacts, specimens.Ex: http://data.datacite.org/10.7299/X78052RB
     */
    @XmlEnumValue("PhysicalObject")
    PHYSICAL_OBJECT("PhysicalObject"),
    /**
     * A version of a scholarly or scientific paper that precedes
     * formal peer review and publication in a peer-reviewed scholarly
     * or scientific journal.
     * <p>
     * &lt;resourceType resourceTypeGeneral="Preprint"&gt;Research Paper&lt;/resourceType&gt;
     */
    @XmlEnumValue("Preprint")
    PREPRINT("Preprint"),
    /**
     * A document that presents information in an organized format for a
     * specific audience and purpose.
     * <p>
     * &lt;resourceType resourceTypeGeneral="Report"&gt;Annual Report&lt;/resourceType&gt;
     */
    @XmlEnumValue("Report")
    REPORT("Report"),
    /**
     * A system that provides one or more functions of value to the end-user.
     * <p>
     * Data management service, authentication service, or photocopying service.
     */
    @XmlEnumValue("Service")
    SERVICE("Service"),
    /**
     * A computer program in source code (text) or compiled form.
     * <p>
     * Software supporting research. Ex:
     * http://data.datacite.org/10.7938/M1057CV9
     */
    @XmlEnumValue("Software")
    SOFTWARE("Software"),
    /**
     * A resource primarily intended to be heard.
     * <p>
     * Audio recording. Ex: http://data.datacite.org/10.7282/T3J67F05
     */
    @XmlEnumValue("Sound")
    SOUND("Sound"),
    /**
     * Something established by authority, custom,
     * or general consent as a model, example, or point of reference.
     * <p>
     * &lt;resourceType resourceTypeGeneral="Standard"&gt;Dublin Core&lt;/resourceType&gt;
     */
    @XmlEnumValue("Standard")
    STANDARD("Standard"),
    /**
     * A resource consisting primarily of words for reading.
     * <p>
     * Grey literature, lab notes, accompanying materials. Ex:
     * http://data.datacite.org/10.5682/9786065914018
     */
    @XmlEnumValue("Text")
    TEXT("Text"),
    /**
     * A structured series of steps which can be executed to produce a final
     * outcome, allowing users a means to specify and enact their work in a more
     * reproducible manner.
     * <p>
     * Computational workflows involving sequential operations made on data by
     * wrapped software and may be specified in a format belonging to a workflow
     * management system, such as Taverna (http://www.taverna.org.uk/).
     */
    @XmlEnumValue("Workflow")
    WORKFLOW("Workflow"),
    /**
     * If selected, supply a value for ResourceType.
     */
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    /**
     * Constructor.
     *
     * @param v resource type
     */
    ResourceType(String v) {
        value = v;
    }

    /**
     * Gets the value.
     *
     * @return the value
     */
    public String value() {
        return value;
    }

    /**
     * Gets the resource type from a value
     *
     * @param v value
     * @return the resource type
     */
    public static ResourceType fromValue(String v) {
        for (ResourceType c: ResourceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
