//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.06 at 03:43:03 PM CEST 
//
package org.datacite.schema.kernel_4;

import fr.cnes.doi.utils.spec.Requirement;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the org.datacite.schema.kernel_4 package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 *
 */
@Requirement(
        reqId = "DOI_SRV_010",
        reqName = "Création de métadonnées"
)
@Requirement(
        reqId = "DOI_SRV_040",
        reqName = "Mise à jour des métadonnées d'un DOI"
)
@Requirement(
        reqId = "DOI_ARCHI_050",
        reqName = "Vérification du schéma de métadonnées"
)
@XmlRegistry
public class ObjectFactory {

    private final static QName _ResourceDescriptionsDescriptionBr_QNAME = new QName("http://datacite.org/schema/kernel-4", "br");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: org.datacite.schema.kernel_4
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Resource }
     *
     * @return
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link Resource.FundingReferences }
     *
     * @return
     */
    public Resource.FundingReferences createResourceFundingReferences() {
        return new Resource.FundingReferences();
    }

    /**
     * Create an instance of {@link Resource.FundingReferences.FundingReference
     * }
     *
     * @return
     */
    public Resource.FundingReferences.FundingReference createResourceFundingReferencesFundingReference() {
        return new Resource.FundingReferences.FundingReference();
    }

    /**
     * Create an instance of {@link Resource.GeoLocations }
     *
     * @return
     */
    public Resource.GeoLocations createResourceGeoLocations() {
        return new Resource.GeoLocations();
    }

    /**
     * Create an instance of {@link Resource.GeoLocations.GeoLocation }
     *
     * @return
     */
    public Resource.GeoLocations.GeoLocation createResourceGeoLocationsGeoLocation() {
        return new Resource.GeoLocations.GeoLocation();
    }

    /**
     * Create an instance of {@link Resource.Descriptions }
     *
     * @return
     */
    public Resource.Descriptions createResourceDescriptions() {
        return new Resource.Descriptions();
    }

    /**
     * Create an instance of {@link Resource.RightsList }
     *
     * @return
     */
    public Resource.RightsList createResourceRightsList() {
        return new Resource.RightsList();
    }

    /**
     * Create an instance of {@link Resource.RelatedIdentifiers }
     *
     * @return
     */
    public Resource.RelatedIdentifiers createResourceRelatedIdentifiers() {
        return new Resource.RelatedIdentifiers();
    }

    /**
     * Create an instance of {@link Resource.AlternateIdentifiers }
     *
     * @return
     */
    public Resource.AlternateIdentifiers createResourceAlternateIdentifiers() {
        return new Resource.AlternateIdentifiers();
    }

    /**
     * Create an instance of {@link Resource.Dates }
     *
     * @return
     */
    public Resource.Dates createResourceDates() {
        return new Resource.Dates();
    }

    /**
     * Create an instance of {@link Resource.Contributors }
     *
     * @return
     */
    public Resource.Contributors createResourceContributors() {
        return new Resource.Contributors();
    }

    /**
     * Create an instance of {@link Resource.Contributors.Contributor }
     *
     * @return
     */
    public Resource.Contributors.Contributor createResourceContributorsContributor() {
        return new Resource.Contributors.Contributor();
    }

    /**
     * Create an instance of {@link Resource.Subjects }
     *
     * @return
     */
    public Resource.Subjects createResourceSubjects() {
        return new Resource.Subjects();
    }

    /**
     * Create an instance of {@link Resource.Titles }
     *
     * @return
     */
    public Resource.Titles createResourceTitles() {
        return new Resource.Titles();
    }

    /**
     * Create an instance of {@link Resource.Creators }
     *
     * @return
     */
    public Resource.Creators createResourceCreators() {
        return new Resource.Creators();
    }

    /**
     * Create an instance of {@link Resource.Creators.Creator }
     *
     * @return
     */
    public Resource.Creators.Creator createResourceCreatorsCreator() {
        return new Resource.Creators.Creator();
    }

    /**
     * Create an instance of {@link Resource.Identifier }
     *
     * @return
     */
    public Resource.Identifier createResourceIdentifier() {
        return new Resource.Identifier();
    }

    /**
     * Create an instance of {@link Resource.ResourceType }
     *
     * @return
     */
    public Resource.ResourceType createResourceResourceType() {
        return new Resource.ResourceType();
    }

    /**
     * Create an instance of {@link Resource.Sizes }
     *
     * @return
     */
    public Resource.Sizes createResourceSizes() {
        return new Resource.Sizes();
    }

    /**
     * Create an instance of {@link Resource.Formats }
     *
     * @return
     */
    public Resource.Formats createResourceFormats() {
        return new Resource.Formats();
    }

    /**
     * Create an instance of {@link Box }
     *
     * @return
     */
    public Box createBox() {
        return new Box();
    }

    /**
     * Create an instance of {@link Point }
     *
     * @return
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link Resource.FundingReferences.FundingReference.FunderIdentifier
     * }
     *
     * @return
     */
    public Resource.FundingReferences.FundingReference.FunderIdentifier createResourceFundingReferencesFundingReferenceFunderIdentifier() {
        return new Resource.FundingReferences.FundingReference.FunderIdentifier();
    }

    /**
     * Create an instance of {@link Resource.FundingReferences.FundingReference.AwardNumber
     * }
     *
     * @return
     */
    public Resource.FundingReferences.FundingReference.AwardNumber createResourceFundingReferencesFundingReferenceAwardNumber() {
        return new Resource.FundingReferences.FundingReference.AwardNumber();
    }

    /**
     * Create an instance of {@link Resource.GeoLocations.GeoLocation.GeoLocationPolygon
     * }
     *
     * @return
     */
    public Resource.GeoLocations.GeoLocation.GeoLocationPolygon createResourceGeoLocationsGeoLocationGeoLocationPolygon() {
        return new Resource.GeoLocations.GeoLocation.GeoLocationPolygon();
    }

    /**
     * Create an instance of {@link Resource.Descriptions.Description }
     *
     * @return
     */
    public Resource.Descriptions.Description createResourceDescriptionsDescription() {
        return new Resource.Descriptions.Description();
    }

    /**
     * Create an instance of {@link Resource.RightsList.Rights }
     *
     * @return
     */
    public Resource.RightsList.Rights createResourceRightsListRights() {
        return new Resource.RightsList.Rights();
    }

    /**
     * Create an instance of {@link Resource.RelatedIdentifiers.RelatedIdentifier
     * }
     *
     * @return
     */
    public Resource.RelatedIdentifiers.RelatedIdentifier createResourceRelatedIdentifiersRelatedIdentifier() {
        return new Resource.RelatedIdentifiers.RelatedIdentifier();
    }

    /**
     * Create an instance of {@link Resource.AlternateIdentifiers.AlternateIdentifier
     * }
     *
     * @return
     */
    public Resource.AlternateIdentifiers.AlternateIdentifier createResourceAlternateIdentifiersAlternateIdentifier() {
        return new Resource.AlternateIdentifiers.AlternateIdentifier();
    }

    /**
     * Create an instance of {@link Resource.Dates.Date }
     *
     * @return
     */
    public Resource.Dates.Date createResourceDatesDate() {
        return new Resource.Dates.Date();
    }

    /**
     * Create an instance of {@link Resource.Contributors.Contributor.NameIdentifier
     * }
     *
     * @return
     */
    public Resource.Contributors.Contributor.NameIdentifier createResourceContributorsContributorNameIdentifier() {
        return new Resource.Contributors.Contributor.NameIdentifier();
    }

    /**
     * Create an instance of {@link Resource.Subjects.Subject }
     *
     * @return
     */
    public Resource.Subjects.Subject createResourceSubjectsSubject() {
        return new Resource.Subjects.Subject();
    }

    /**
     * Create an instance of {@link Resource.Titles.Title }
     *
     * @return
     */
    public Resource.Titles.Title createResourceTitlesTitle() {
        return new Resource.Titles.Title();
    }

    /**
     * Create an instance of {@link Resource.Creators.Creator.NameIdentifier }
     *
     * @return
     */
    public Resource.Creators.Creator.NameIdentifier createResourceCreatorsCreatorNameIdentifier() {
        return new Resource.Creators.Creator.NameIdentifier();
    }

    /**
     * Create an instance of
     * {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     * @param value
     * @return
     */
    @XmlElementDecl(namespace = "http://datacite.org/schema/kernel-4", name = "br", scope = Resource.Descriptions.Description.class)
    public JAXBElement<String> createResourceDescriptionsDescriptionBr(String value) {
        return new JAXBElement<String>(_ResourceDescriptionsDescriptionBr_QNAME, String.class, Resource.Descriptions.Description.class, value);
    }

}
