swagger: "2.0"

info:
  version: "1.0.0"
  title: Doi Server API
  description: A Digital Object Identifier (DOI) is an alphanumeric string assigned to uniquely identify an object. It is tied to a metadata description of the object as well as to a digital location, such as a URL, where all the details about the object are accessible. This documentation provides an API to query the DOI-server.
  contact:
    name: CNES (DNO/ISA/VIP)
    email : jean-christophe.malapert@cnes.fr
    url: 'http://cnes.fr'
  license:
    name: LGPL
    url: 'https://www.gnu.org/licenses/lgpl-3.0.txt'
host: localhost:8182
basePath: /
schemes: [https,http]


tags:
 - name: "DataCite Metadata Store (MDS) API"
   description: "Allows users to register DataCite DOIs and associated metadata"
 - name: "DOI Citation Formatter"
   description: "Allows user to format a citation based on the DOI metadata "
 - name: "Administration"
   description: "Allows registered users to create token"
   externalDocs:
    description: "Find out more about our DOI-server"
    url: "https://cnes.github.io/DOI-server"
    
security:
 - APIKeyHeader: []
 
    
paths:
  /admin/token:
    post:
      produces:
      - text
      consumes:
      - application/x-www-form-urlencoded      
      tags:
      - "Administration"      
      description: Create a token
      security:
        - basicAuth: []
      operationId: createToken        
      responses:
        200:
          description: OK (successfully authenticated)
          schema:
            type: string          
            
  /mds/dois:
    post:
      produces:
      - application/json
      consumes:
      - application/x-www-form-urlencoded
      tags:
      - "DataCite Metadata Store (MDS) API"
      description: Create a **new** doi project or update the landing page url if it the project already exists
      operationId: postLandingPage
      parameters:
        - name: selectedRole
          in: header
          description: the selected role when a user is connected to more than 2 roles.
          required: false
          type: string    
        - name: url
          in: formData
          description: the URL of the landing page
          required: true
          type: string
        
        - name: doi
          in: formData
          description: the project suffix, which is an unique identifier within the project
          required: true
          type: string  
          
      responses:
        201:
          description: Operation successful

        400:
          description: Validation error when defining the DOI and its landing page
   
        401:
          description: Expired token
  
        403:
          description: Forbidden
            
        412:
          description: Metadata must be uploaded first
   
        500:
          description: Interface problem between Datacite and DOI-Server

  
  /mds/metadata:
    post:
      tags:
      - "DataCite Metadata Store (MDS) API"
      consumes:
      - application/xml
      description: Create or update doi project metadata
      operationId: postDoiMetadata
      parameters:
        - name: selectedRole
          in: header
          description: the selected role when a user is connected to more than 2 roles.
          required: false
          type: string        
        - name: metadata
          in: body
          description: metadata
          required: true
          schema: 
            type: string
            
      responses:
        201:
          description: Operation successfull

        400:
          description: Failed to validate the user inputs parameters
        
        401:
          description: Unauthorized - no login
          
        403:
          description: Forbidden - login problem or dataset belongs to another party
         
        500:
          description: Interface problem between Datacite and DOI-Server"
 

  /mds/dois/{prefix}/{project}/{doi_name}:
    get:
      produces:
      - application/json
      tags:
      - "DataCite Metadata Store (MDS) API"
      description: Retrieves the landing page URL
      operationId: getLandingPageUrl
      parameters:
        - name: prefix
          in: path
          type: string
          description: DOI prefix
          required: true
        - name: project
          in: path
          type: string
          description: Project identifier
          required: true
        - name: doi_name
          in: path
          type: string
          description: Record ID
          required: true
      responses:
        200:
          description: The landing page was retrieved successfully
          schema:
            type: string
        
        204:
          description: the DOI is known to MDS, but is not minted (or not resolvable e.g. due to handle's latency)
          schema:
            type: string        
        401:
          description: Unauthorized - no login
          schema:
            type: string          
        403:
          description: Forbidden - login problem or dataset belongs to another party
          schema:
            type: string 
          
        404: 
          description: DOI does not exist in our database
          schema:
            type:  string
        500:
          description: Internal Server Error - server internal error
          schema:
            type: string          

  /mds/metadata/{prefix}/{project}/{doi_name}:
    get:
      tags:
      - "DataCite Metadata Store (MDS) API"
      produces:
      - application/xml
      description: Renvoie les metadata d'un doi
      operationId: getAllDoiMetadata
      parameters:
        - name: prefix
          in: path
          type: string
          description: DOI prefix
          required: true
        - name: project
          in: path
          type: string
          description: Project identifier
          required: true
        - name: doi_name
          in: path
          type: string
          description: Record ID
          required: true

      responses:
        200:
          description: Successful metadata of given doi project retrieval
          schema:
            type: string
            
        401:
          description: Unauthorized - no login
          
        403:
          description: Forbidden - login problem or dataset belongs to another party
          
        404:
          description: Not Found - DOI does not exist in our database
          
        410:
          description: Gone - the requested dataset was marked inactive
        
        500:
          description: Internal Server Error - server internal error 
         
            
    delete:
      tags:
      - "DataCite Metadata Store (MDS) API"
      description: This request marks a dataset as 'inactive'
      operationId: cancelDoiProject
      parameters:
        - name: selectedRole
          in: header
          description: the selected role when a user is connected to more than 2 roles.
          required: false
          type: string      
        - name: prefix
          in: path
          type: string
          description: DOI prefix
          required: true
        - name: project
          in: path
          type: string
          description: Project identifier
          required: true
        - name: doi_name
          in: path
          type: string
          description: Record ID
          required: true
      responses:
        202:
          description: Cancelling taken into account and return metadata that was deactivated
          schema:
            type: string
          
        401:
          description: Unauthorized - no login
          
        403:
          description: Forbidden - login problem or dataset belongs to another party
          
        404:
          description: Not Found - DOI does not exist in our database
          
        500:
          description: Internal Server Error
          
            
  
  /mds/media/{prefix}/{project}/{doi_name}:
    get:
      produces:
      - text/uri-list
      tags:
      - "DataCite Metadata Store (MDS) API" 
      description: Retuen a list of pairs of media type and URLs
      operationId: getDoiMedia
      parameters:
        - name: selectedRole
          in: header
          description: the selected role when a user is connected to more than 2 roles.
          required: false
          type: string      
        - name: prefix
          in: path
          type: string
          description: DOI prefix
          required: true
        - name: project
          in: path
          type: string
          description: Project identifier
          required: true
        - name: doi_name
          in: path
          type: string
          description: Record ID
          required: true
          
      responses:
      
        200:
          description: Successful media retrieval          
          schema:
            type: string
            
        500:
          description: Internal Server Error    
              
    post:
      tags:
      - "DataCite Metadata Store (MDS) API"
      consumes:
      - application/x-www-form-urlencoded
      description: add an association media/url
      operationId: postMedia
      parameters:
        - name: selectedRole
          in: header
          description: the selected role when a user is connected to more than 2 roles.
          required: false
          type: string      
        - name: prefix
          in: path
          type: string
          description: DOI prefix
          required: true
        - name: project
          in: path
          type: string
          description: Project identifier
          required: true
        - name: doi_name
          in: path
          type: string
          description: Record ID
          required: true
      responses:
        200:
          description: Successful adding association

          
  /citation/language:
    get:
      tags:
      - "DOI Citation Formatter"
      description: Renvoie la liste des langages disponibles
      operationId: getCitationsLanguage
      responses:
        200:
          description: The languages was retrieved successfully
          schema:
            type: array
            items:
              type: string
        500:
          description: Other type of errors
             
  
  /citation/style:
    get:
      tags:
      - "DOI Citation Formatter"
      description: Renvoie la liste des styles disponibles
      operationId: getCitationsStyle
      responses:
        200:
          description: The styles was retrieved successfully
          schema:
            type: array
            items:
              type: string
        500:
          description: Other type of errors
            
  /citation/format:
    get:
      tags:
      - "DOI Citation Formatter"
      description: Returns the formatted citation
      operationId: getCitation
      parameters:
        - name: doi
          in: query
          description: DOI project name
          required: true
          type: string
        - name: style
          in: query
          description: style
          required: true
          type: string
          
        - name: lang
          in: query
          description: langage
          required: true
          type: string
             
      responses:
        200:
          description: The citation was retrieved successfully
          schema:
            type: string
        500:
          description: Other type of error
             
securityDefinitions:
  APIKeyHeader:
    type: apiKey
    in: header
    name: Authorization
  basicAuth:
    type: basic
